[package]
name = "databend-storages-common-table-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
dev = ["snap"]

[dependencies]
arrow = { workspace = true }
bincode = "1.3.3"
chrono = { workspace = true }
databend-common-arrow = { workspace = true }
databend-common-base = { workspace = true }
databend-common-datavalues = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-io = { workspace = true }
databend-common-storage = { path = "../../../../common/storage" }
enum-as-inner = "0.5"
parquet = { workspace = true }
rmp-serde = "1.1.1"
serde = { workspace = true }
serde_json = { workspace = true }
simple_hll = { version = "0.0.1", features = ["serde_borsh"] }
snap = { version = "1.1.0", optional = true }
typetag = { workspace = true }
zstd = "0.12.3"
[dev-dependencies]
pot = "2.0.0"

[lints]
workspace = true
